### PR TITLE
Mr heart changes

### PR DESCRIPTION
**Pull request by MrHeart**
Add Note section and comments in the code to help in selection of the right classes.  Also add windows equivalent of Mac's `option+enter`

### CODE REVIEW

**Comment by shekhargulati** [comment]
@MrHeart thanks for your PR.

**Comment by shekhargulati** [comment]
@MrHeart I had to revert your PR because you have changed name of the `README.md` file. Please don't location and name of files. Can you create another PR without changing name of the file?

**Comment by MrHeart** [comment]
ok, thanks for your patience.

I’ll create another pull request now without changing the name of the file.

Thanks so much

Sent from Windows Mail

From: Shekhar Gulati
Sent: ‎Thursday‎, ‎June‎ ‎30‎, ‎2016 ‎4‎:‎18‎ ‎AM
To: shekhargulati/52-technologies-in-2016
Cc: Ojabo John Heart, Mention

@MrHeart I had to revert your PR because you have changed name of the README.md file. Please don't location and name of files. Can you create another PR without changing name of the file?

**Comment by shekhargulati** [comment]
@MrHeart no issues.

**Pull request merged**
